- name: Ensure "{{file_path}}" directory exists
  file:
    path: "{{file_path}}"
    state: directory
    owner: "{{user_name}}"
    group: "{{group_name}}"
    mode: 0750

    # Copy file to the directory
- name: Copy File to "{{file_path}}"
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{user_name}}"
    group: "{{group_name}}"
    mode: 0750
  with_items:
    - "{{file_templates}}"